name: fastapi-auth-service

services:
  auth-db:
    image: postgres:16
    container_name: ${POSTGRES_DB}
    env_file:
      - ./.env
    volumes:
      - auth-database:/var/lib/postgresql/data
    expose:
      - ${POSTGRES_PORT}
    restart: always
    networks:
      - shared-network

  auth-cache:
    image: redis
    container_name: ${REDIS_DB}
    expose:
      - ${REDIS_PORT}
    volumes:
      - auth-rds-data:/data
      - auth.redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
    networks:
      - shared-network

  auth-nginx:
    image: nginx:alpine3.18
    container_name: auth-nginx
    ports:
      - ${SERVICE_PORT}:${NGINX_PORT}
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - shared-network

  auth-service:
    build: .
    container_name: auth_service
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - auth-db
      - auth-cache
      - auth-nginx
    networks:
      - shared-network

volumes:
  auth-database:
  auth-rds-data:
  auth.redis.conf:


networks:
  shared-network:
    external: true
