"""user_device_type

Revision ID: fd638091eaef
Revises: c0f263127b8b
Create Date: 2024-12-23 15:20:19.637660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd638091eaef'
down_revision: Union[str, None] = 'c0f263127b8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('user_device_type', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'refresh_tokens', ['id'])
    op.create_unique_constraint(None, 'roles', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_constraint(None, 'refresh_tokens', type_='unique')
    op.drop_column('refresh_tokens', 'user_device_type')
    # ### end Alembic commands ###
