name: fastapi-notifications-service

services:
  notifications-db:
    image: postgres:16
    container_name: ${POSTGRES_DB}
    env_file:
      - ./.env
    volumes:
      - notifications-database:/var/lib/postgresql/data
    expose:
      - ${POSTGRES_PORT}
    restart: always
    networks:
      - shared-network

  notifications-cache:
    image: redis
    container_name: ${REDIS_DB}
    expose:
      - ${REDIS_PORT}
    volumes:
      - notifications-rds-data:/data
      - notifications.redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
    networks:
      - shared-network

  notifications-nginx:
    image: nginx:alpine3.18
    container_name: notifications-nginx
    ports:
      - ${SERVICE_PORT}:${NGINX_PORT}
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - shared-network

  notifications-service:
    build: .
    container_name: notifications_service
    command: /entrypoint-fastapi.sh
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - notifications-db
      - notifications-cache
      - notifications-nginx
    networks:
      - shared-network

  notifications-celery:
    build: .
    container_name: notifications_celery
    command: /entrypoint-celery.sh
    env_file:
      - .env
    depends_on:
      - notifications-service
    networks:
      - shared-network

volumes:
  notifications-database:
  notifications-rds-data:
  notifications.redis.conf:


networks:
  shared-network:
    external: true
